# fly.toml app configuration file generated for lineageos-nibbler on 2023-04-30T18:51:51-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lineageos-nibbler"
primary_region = "sea"
kill_signal = "SIGINT"
kill_timeout = "5s"

[env]
  PYTHONUNBUFFERED = "true"
  REDIS_DB = "0"
  REDIS_HOST = "localhost"
  REDIS_PORT = "6379"

[[mounts]]
  destination = "/data"
  source = "redis"

[metrics]
  port = 9091
  path = "/metrics"
